In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

In [3]:
s[2]
## 50

50

In [4]:
len(s)
## 4

4

Задание 2.1
1 point possible (graded)
Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Будем считать, что температура в январе — , то есть отсчёт индексов идёт с нуля.

Выберите неверное утверждение:
 — средняя температура воздуха в июне

Минимальная средняя температура воздуха в Риме достигается в январе

 — средняя температура воздуха в феврале
 
Максимальная средняя температура воздуха в Риме достигается в июле

In [5]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [9]:
print(t[5])
print(min(t))
print(t[1])
print(max(t))

28
12
14
31


In [11]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
## array([15, 23, 14,  8])
print(a - b)
## array([ 5, -7, -4, -6])

[15 23 14  8]
[ 5 -7 -4 -6]


In [13]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [14]:
a = np.array([2, 3, 2.5])
omega = 72
c = a * omega
c

array([144., 216., 180.])

In [16]:
d = np.array([120, 150, 190])
e = np.array([130, 130, 130])
c+d+e

array([394., 496., 500.])

In [17]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([1800, 3000, 2700])

Задание 2.7
1 point possible (graded)
Найдите линейную комбинацию векторов  с коэффициентами 2, -3 и 5 соответственно.

In [19]:
a = np.array([4, 5])
b = np.array([2, 1])
c = np.array([1, 0])

2*a-3*b+5*c

array([7, 7])

Задание 2.8
1 point possible (graded)
Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

In [21]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])

400*b-200*a

array([-200, 1200,  200,  600])

In [22]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [23]:
a = np.array([4, 5, -1])
b = np.array([2, 0, 1])

np.dot(a, b)

7