In [2]:
import numpy as np

In [3]:
s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

In [4]:
s[2]
## 50

50

In [5]:
len(s)
## 4

4

Задание 2.1
1 point possible (graded)
Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Будем считать, что температура в январе — , то есть отсчёт индексов идёт с нуля.

Выберите неверное утверждение:
 — средняя температура воздуха в июне

Минимальная средняя температура воздуха в Риме достигается в январе

 — средняя температура воздуха в феврале
 
Максимальная средняя температура воздуха в Риме достигается в июле

In [6]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [7]:
print(t[5])
print(min(t))
print(t[1])
print(max(t))

28
12
14
31


In [8]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
## array([15, 23, 14,  8])
print(a - b)
## array([ 5, -7, -4, -6])

[15 23 14  8]
[ 5 -7 -4 -6]


In [9]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [10]:
a = np.array([2, 3, 2.5])
omega = 72
c = a * omega
c

array([144., 216., 180.])

In [11]:
d = np.array([120, 150, 190])
e = np.array([130, 130, 130])
c+d+e

array([394., 496., 500.])

In [12]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([1800, 3000, 2700])

Задание 2.7
1 point possible (graded)
Найдите линейную комбинацию векторов  с коэффициентами 2, -3 и 5 соответственно.

In [13]:
a = np.array([4, 5])
b = np.array([2, 1])
c = np.array([1, 0])

2*a-3*b+5*c

array([7, 7])

Задание 2.8
1 point possible (graded)
Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

In [14]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])

400*b-200*a

array([-200, 1200,  200,  600])

In [15]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [16]:
a = np.array([4, 5, -1])
b = np.array([2, 0, 1])

np.dot(a, b)

7

In [17]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

Hut_Paradise_values = Hut_Paradise_DF.values
  
Выберите координаты данного вектора:

In [18]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [19]:
Hut_Paradise_values[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [20]:
Hut_Paradise_values[:, 1] - Hut_Paradise_values[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Задание 3.6
1 point possible (graded)
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [21]:
view_time = [10, 20, 30, 15, 5, 40, 20, 8, 20]

In [22]:
Hut_Paradise_values[:, 4] @ view_time

1348

In [23]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [24]:
c= 2*v - 3*w

In [25]:
c@u

0

4/13   4. Основные понятия линейной алгебры: матрицы и базовые действия с ними

In [26]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [27]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


In [28]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [31]:
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [32]:
cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [34]:
inc = inc * 0.87

In [35]:
inc - cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

6/13   6. Матричное умножение

In [36]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [37]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [38]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [39]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [40]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [42]:
c = np.matrix('1, 2, 1; 1, -1, 2')

In [43]:
c

matrix([[ 1,  2,  1],
        [ 1, -1,  2]])

In [44]:
c.T *c

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])