In [69]:
import numpy as np

In [70]:
s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

In [71]:
s[2]
## 50

50

In [72]:
len(s)
## 4

4

Задание 2.1
1 point possible (graded)
Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Будем считать, что температура в январе — , то есть отсчёт индексов идёт с нуля.

Выберите неверное утверждение:
 — средняя температура воздуха в июне

Минимальная средняя температура воздуха в Риме достигается в январе

 — средняя температура воздуха в феврале
 
Максимальная средняя температура воздуха в Риме достигается в июле

In [73]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [74]:
print(t[5])
print(min(t))
print(t[1])
print(max(t))

28
12
14
31


In [75]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
## array([15, 23, 14,  8])
print(a - b)
## array([ 5, -7, -4, -6])

[15 23 14  8]
[ 5 -7 -4 -6]


In [76]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [77]:
a = np.array([2, 3, 2.5])
omega = 72
c = a * omega
c

array([144., 216., 180.])

In [78]:
d = np.array([120, 150, 190])
e = np.array([130, 130, 130])
c+d+e

array([394., 496., 500.])

In [79]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([1800, 3000, 2700])

Задание 2.7
1 point possible (graded)
Найдите линейную комбинацию векторов  с коэффициентами 2, -3 и 5 соответственно.

In [80]:
a = np.array([4, 5])
b = np.array([2, 1])
c = np.array([1, 0])

2*a-3*b+5*c

array([7, 7])

Задание 2.8
1 point possible (graded)
Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

In [81]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])

400*b-200*a

array([-200, 1200,  200,  600])

In [82]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [83]:
a = np.array([4, 5, -1])
b = np.array([2, 0, 1])

np.dot(a, b)

7

In [84]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

Hut_Paradise_values = Hut_Paradise_DF.values
  
Выберите координаты данного вектора:

In [85]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [86]:
Hut_Paradise_values[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [87]:
Hut_Paradise_values[:, 1] - Hut_Paradise_values[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Задание 3.6
1 point possible (graded)
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [88]:
view_time = [10, 20, 30, 15, 5, 40, 20, 8, 20]

In [89]:
Hut_Paradise_values[:, 4] @ view_time

1348

In [90]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [91]:
c= 2*v - 3*w

In [92]:
c@u

0

4/13   4. Основные понятия линейной алгебры: матрицы и базовые действия с ними

In [93]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [94]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


In [95]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [96]:
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [97]:
cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [98]:
inc = inc * 0.87

In [99]:
inc - cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

6/13   6. Матричное умножение

In [100]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [101]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [102]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [103]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [104]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [105]:
c = np.matrix('1, 2, 1; 1, -1, 2')

In [106]:
c

matrix([[ 1,  2,  1],
        [ 1, -1,  2]])

In [107]:
c.T *c

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

Задание 7.1
1 point possible (graded)
Даны матрица  и вектор 
х
:

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
Найдите произведение матрицы  и вектора 
х
 в том порядке, в котором их можно умножить.

В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

In [108]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [109]:
A@x

array([26, 30])

Задание 7.2
1 point possible (graded)
Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [110]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [111]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Задание 7.3
1 point possible (graded)

Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Составьте матрицу , расположив векторы , ,  в строках. Найдите матрицу Грама  (матрицу скалярных произведений столбцов матрицы ) системы векторов , , .

Чему равна полученная матрица Грама ?

In [112]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [113]:
C = np.matrix([x, y, z])

In [114]:
C.T*C

matrix([[ 6,  3,  0,  2,  4],
        [ 3,  6,  0,  1,  8],
        [ 0,  0,  3, -1,  4],
        [ 2,  1, -1,  1,  0],
        [ 4,  8,  4,  0, 16]])

Условие для заданий 7.4 и 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [115]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [116]:
print(Count_DF)
print(Price_DF)

       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28
       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5         

In [117]:
Count_DF.values.T

array([[10,  2, 12,  4,  6, 10, 22,  7],
       [ 5, 21, 12,  8, 25,  3,  1,  0],
       [12,  3,  0, 18, 27,  2,  4, 31],
       [15, 25, 30, 14, 25, 17, 25, 31],
       [10,  6,  4,  5, 18, 12, 20, 28]], dtype=int64)

In [118]:
Price_DF.values 

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [119]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
c = Count_DF.values * Price_DF.values

In [121]:
c_int = c@ com
c_int

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Задание 7.5
1 point possible (graded)

Найдите вектор дохода стилистов.

Выберите координаты полученного вектора:

In [122]:
Count_DF.values * Price_DF.values

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [123]:
c = Count_DF.values * Price_DF.values
(c @ np.array([1, 1, 1, 1, 1])) -c_int

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

10. Практика: обратная матрица, определитель, ранг

In [124]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [125]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [126]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Задание 10.2
1 point possible (graded)
Найдите ранг системы векторов , , , . Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [127]:
np.linalg.matrix_rank(np.matrix([v1, v2, v3, v4]))

4

Задание 10.4
1 point possible (graded)
Найдите матрицу Грама системы векторов , , , : . В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [130]:
A = np.matrix([v1, v2, v3, v4])
G = A@A.T
G

matrix([[360,  96,  73, -35],
        [ 96,  46,  16,   4],
        [ 73,  16,  33,   4],
        [-35,   4,   4,  51]])

Задание 10.5
1 point possible (graded)
Найдите определитель матрицы Грама  системы , , , . Ответ округлите до целого числа.

In [133]:
round(np.linalg.det(G), 0)

3716648.0

Задание 10.7
1 point possible (graded)
Найдите обратную матрицу к матрице Грама  системы , , , . В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [134]:
np.linalg.inv(G)

matrix([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
        [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
        [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
        [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])