In [3]:
from sympy import symbols, cos, diff

a, b, c = symbols('a b c', real=True)
f = 5*a*b - a*cos(c) + a**8 + c**2*b

print(diff(f, a))

8*a**7 + 5*b - cos(c)


In [8]:
import numpy as np
A = np.array([
    [-6, -12],
    [-12, -6]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)

In [9]:
eig_values

array([  6., -18.])

In [10]:
from sympy import *
 
x, y = symbols('x, y')
eq1 = Eq(8*x-6*y-34, 0)
eq2 = Eq(-6*x+10*y+42, 0)
 
sol = solve([eq1, eq2], [x, y])

In [11]:
sol

{x: 2, y: -3}

In [12]:
from sympy import *
 
x, y = symbols('x, y')
eq1 = Eq(3*x**2-3*y, 0)
eq2 = Eq(3*y**2-3*x, 0)
 
sol = solve([eq1, eq2], [x, y])
sol

[(0, 0),
 (1, 1),
 ((-1/2 - sqrt(3)*I/2)**2, -1/2 - sqrt(3)*I/2),
 ((-1/2 + sqrt(3)*I/2)**2, -1/2 + sqrt(3)*I/2)]

In [14]:
import numpy as np
A = np.array([
    [6, -3],
    [-3, 6]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
eig_values

array([9., 3.])

5. Условные экстремумы. Метод Лагранжа

In [1]:
from sympy import *
a,b,w=symbols(' a b w' )
g = 3*a**2 + a + 4*b + 5*b**2
print('Целевая функция для аргументов a и b :\n f = ', g)
q = a + b - 200
print('Функция ограничений: ', q,'= 0')
f = 3*a**2 + a + 4*b + 5*b**2 + w*(a + b - 200)
print('Функция Лагранжа :\n ',f)
fa = f.diff(a)
print('df/da =',fa,'= 0')
fb = f.diff(b)
print('df/db =',fb,'= 0')
fw = f.diff(w)
print('df/dw =',fw,'= 0')
sols = solve([fa,fb,fw],a,b,w)
print('Стационарная точка M(x,y):\n',float(sols[a]),',',float(sols[b]))

#Целевая функция для аргументов a и b :
#f =  3*a**2 + a + 5*b**2 + 4*b
#Функция ограничений:  a + b - 200 = 0
#Функция Лагранжа :
#3*a**2 + a + 5*b**2 + 4*b + w*(a + b - 200)
#df/da = 6*a + w + 1 = 0
#df/db = 10*b + w + 4 = 0
#df/dw = a + b - 200 = 0
#Стационарная точка M(x,y):
#125.1875 , 74.8125

Целевая функция для аргументов a и b :
 f =  3*a**2 + a + 5*b**2 + 4*b
Функция ограничений:  a + b - 200 = 0
Функция Лагранжа :
  3*a**2 + a + 5*b**2 + 4*b + w*(a + b - 200)
df/da = 6*a + w + 1 = 0
df/db = 10*b + w + 4 = 0
df/dw = a + b - 200 = 0
Стационарная точка M(x,y):
 125.1875 , 74.8125


In [7]:
g = (a - 2)**2 + (b - 1)**2
q = a + b - 1
f = (a - 2)**2 + (b - 1)**2 + w*(a + b - 1)
fa = f.diff(a)
print('df/da =',fa,'= 0')
fb = f.diff(b)
print('df/db =',fb,'= 0')
fw = f.diff(w)
print('df/dw =',fw,'= 0')
sols = solve([fa,fb,fw],a,b,w)
print(float((sols[a] - 2)**2 + (sols[b] - 1)**2))
# print('Стационарная точка M(x,y):\n',float(sols[a]),',',float(sols[b]))

df/da = 2*a + w - 4 = 0
df/db = 2*b + w - 2 = 0
df/dw = a + b - 1 = 0
2.0


In [14]:
a,b,c,w=symbols(' a b c w' )
g = 2*(a*b+b*c+c*a)
q = a*b*c - 1
f = 2*(a*b+b*c+c*a) + w*(a*b*c - 1)
fa = f.diff(a)
print('df/da =',fa,'= 0')
fb = f.diff(b)
print('df/db =',fb,'= 0')
fc = f.diff(c)
print('df/db =',fc,'= 0')
fw = f.diff(w)
print('df/dw =',fw,'= 0')
sols = solve([fa,fb,fc,fw],a,b,c,w)
print(2*(sols[0][0]*sols[0][1]+sols[0][1]*sols[0][2]+sols[0][2]*sols[0][0]))
# sols

df/da = b*c*w + 2*b + 2*c = 0
df/db = a*c*w + 2*a + 2*c = 0
df/db = a*b*w + 2*a + 2*b = 0
df/dw = a*b*c - 1 = 0
6


In [15]:
# Импортируем все необходимые функции из библиотеки SymPy
from sympy import init_printing, solve, symbols

# Подключаем аккуратный вывод формул
init_printing()

# Создаём переменные
x1, x2, x1_tilde, lambda1, lambda2 = symbols(
    "x_1 x_2 xtilde_2 \lambda_1 \lambda_2", real=True
)

# Пишем систему уравнений для переменных
dLdx1 = -x2 + lambda1 - lambda2
dLdx2 = -x1 + lambda1
dLdx1_tilde = 2 * lambda2 * x1_tilde
dLdlambda1 = x1 + x2 - 10
dLdlambda2 = -x1 + 6 + x1_tilde**2

# Решаем систему уравнений с помощью функции solve
solution = solve(
    [dLdx1, dLdx2, dLdx1_tilde, dLdlambda1, dLdlambda2],
    x1,
    x2,
    x1_tilde,
    lambda1,
    lambda2,
)

print(solution)

[(6, 4, 0, 6, 2)]


6. Градиент и антиградиент

In [16]:
import numpy as np

In [17]:
f = np.array([3, 7, 14, 23, 36, 47], dtype=float)
 
np.gradient(f)

# array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

In [18]:
print(f[1] - f[0], f[-1] - f[-2])

# (4.0, 11.0)

4.0 11.0


In [19]:
(f[2] - f[0])/2 # 5.5
(f[3] - f[1])/2 # 8.0
(f[4] - f[2])/2 # 11.0
(f[5] - f[3])/2 # 12.0

In [20]:
np.gradient(f, 2)

# array([2.  , 2.75, 4.  , 5.5 , 6.  , 5.5 ])

for i in range(1, len(f) - 1):
    print((f[i + 1] - f[i - 1])/(2*2))
#2.75
#4.0
#5.5
#6.0

2.75
4.0
5.5
6.0


In [22]:
a,b,c,w=symbols(' a b c w' )
fa = -2*(2.1 - a-b) -2*(2.9-a-3*b) - 2*(4.1-a-5*b)
print('df/db =',fc,'= 0')
fb = -2*(2.1 - a-b) -6*(2.9-a-3*b) - 10*(4.1-a-5*b)
print('df/dw =',fw,'= 0')
sols = solve([fa,fb],a,b)
sols

df/db = a*b*w + 2*a + 2*b = 0
df/dw = a*b*c - 1 = 0


In [39]:
f = np.array([8, 2, 8, 3, 5, 6, 5, 15])
np.gradient(f, 7)[7]


In [38]:
for i in range(1, len(f)-1):
    print((f[i + 1] - f[i - 1])/(2*7))

0.0
0.07142857142857142
-0.21428571428571427
0.21428571428571427
0.0
0.6428571428571429
