In [2]:
import numpy as np

In [3]:
v1 = np.array([-1, 2, -7, 9])
v2 = np.array([2, 8, 2, -1])

In [4]:
v1@v2

-9

In [5]:
A = np.matrix('1,1;1,2')
A

matrix([[1, 1],
        [1, 2]])

In [6]:
A@A.T

matrix([[2, 3],
        [3, 5]])

In [7]:
A = np.matrix('1,2;3,7')

In [8]:
np.linalg.inv(A)

matrix([[ 7., -2.],
        [-3.,  1.]])

In [13]:
A = np.matrix('4,7;5,10')

In [12]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[ 2. , -1.4],
        [-1. ,  0.8]])

In [14]:
A = np.matrix('1,2;-3,1;1,2;1,-1')
A

matrix([[ 1,  2],
        [-3,  1],
        [ 1,  2],
        [ 1, -1]])

In [18]:
C = A.T@A

In [20]:
D = np.linalg.inv(C)
D

matrix([[0.08333333, 0.        ],
        [0.        , 0.1       ]])

In [21]:
A.T@np.array([1, 4, 5, 0])

matrix([[-6, 16]])

In [22]:
D@A.T@np.array([1, 4, 5, 0])

matrix([[-0.5,  1.6]])