In [2]:
import pandas as pd
import numpy as np


## 1. Импорт и  первичный анализ данных

In [8]:
sample_a = pd.read_csv('data/sample_a.zip')
sample_b = pd.read_csv('data/sample_b.zip')
sample_c = pd.read_csv('data/sample_c.zip')

display(sample_a.head(), sample_b.head(), sample_c.head())

user_id  item_id  action_id
0    84636      360          1
1    21217     9635          1
2    13445     8590          1
3    38450     5585          1
4    14160     2383          0

user_id  item_id  action_id
0   118375     4105          1
1   107569     8204          1
2   175990      880          1
3   160582     9568          0
4   123400     4000          1

user_id  item_id  action_id
0   274623     2863          1
1   265472      343          1
2   242779     6009          0
3   275009     2184          1
4   268104     3134          2

In [11]:
display(sample_a.shape, sample_b.shape, sample_c.shape)

(1188912, 3)

(1198438, 3)

(1205510, 3)

In [23]:
display(sample_a.info(), sample_b.info(), sample_c.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188912 entries, 0 to 1188911
Data columns (total 3 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1188912 non-null  int64
 1   item_id    1188912 non-null  int64
 2   action_id  1188912 non-null  int64
dtypes: int64(3)
memory usage: 27.2 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1198438 entries, 0 to 1198437
Data columns (total 3 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1198438 non-null  int64
 1   item_id    1198438 non-null  int64
 2   action_id  1198438 non-null  int64
dtypes: int64(3)
memory usage: 27.4 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205510 entries, 0 to 1205509
Data columns (total 3 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1205510 non-null  int64
 1   item_id    1205510 non-null  int64
 2   action_id  1205510 no

None

None

None

In [25]:
display(sample_a.isna().sum(), sample_b.isna().sum(), sample_c.isna().sum())

user_id      0
item_id      0
action_id    0
dtype: int64

user_id      0
item_id      0
action_id    0
dtype: int64

user_id      0
item_id      0
action_id    0
dtype: int64

In [9]:
item_prices = pd.read_csv('data/item_prices.zip')
item_prices.head()

item_id  item_price
0      338        1501
1       74         647
2     7696         825
3      866         875
4     5876         804

In [ ]:
item_prices.shape

(1000, 2)

In [24]:
item_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_id     1000 non-null   int64
 1   item_price  1000 non-null   int64
dtypes: int64(2)
memory usage: 15.8 KB


In [26]:
item_prices.isna().sum()

item_id       0
item_price    0
dtype: int64

## 2. Проверка, что нет ситуаций, когда происходит покупка/клик без действия просмотра. Удаление дублей.

Первым делом удалим дубликаты при их наличии. 

In [27]:
sample_a.drop_duplicates(inplace=True)
sample_a.shape

(1188912, 3)

In [28]:
sample_b.drop_duplicates(inplace=True)
sample_b.shape

(1198438, 3)

In [29]:
sample_c.drop_duplicates(inplace=True)
sample_c.shape

(1205510, 3)

In [43]:
item_prices.drop_duplicates(inplace=True)
item_prices.shape

(1000, 2)

Проверим наборы данных на наличие записей о покупке товара без просмотре. При сведении в сводную таблицу по 'user_id' и 'item_id' у товара, который купили без просмотра сумма по столбцу'action_id' должна быть равна 2.

In [40]:
df = sample_a.pivot_table(index=['user_id', 'item_id'], aggfunc='sum')
df.action_id.unique()

array([1, 3], dtype=int64)

In [41]:
df = sample_b.pivot_table(index=['user_id', 'item_id'], aggfunc='sum')
df.action_id.unique()

array([1, 3], dtype=int64)

In [42]:
df = sample_c.pivot_table(index=['user_id', 'item_id'], aggfunc='sum')
df.action_id.unique()

array([1, 3], dtype=int64)

В наборах данных отсутствуют данные о товарах купленных без просмотра.