In [1]:
import numpy as np

In [19]:
v1 = np.array([4,7,-1]).transpose()
v1
v2 = np.array([-4,2,5]).transpose()
v3 = np.array([0,9,4]).transpose()

In [20]:
A1=np.array([v1, v2, v3])
print('A1:\n',A1)

A1:
 [[ 4  7 -1]
 [-4  2  5]
 [ 0  9  4]]


In [22]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 2


In [5]:
A1_inv=np.linalg.inv(A1)

LinAlgError: Singular matrix